-
 name: Deploy MySQL
 hosts: dbservers
 vars:
   mysql_root_password: Nexeas@18
 tasks:
   - name: Install MySQL
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - mysql-client
      - mysql-server
     become: yes
   - name: Start the MySQL service
     become: yes
     service: 
      name: mysql 
      state: started
      enabled: true
   - name: update mysql root password for all root accounts
     become: yes
     mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
     with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 