-
 name: Install Kafka
 hosts: localhost
 tasks:
   - name: Copy Kafka TAR
     get_url: 
       url: http://www-us.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz
       dest: /home/osboxes/Softwares
     become: yes
   - name: Extract files
     unarchive: 
       src: /home/osboxes/Softwares/kafka_2.13-2.7.0.tgz
       dest: /home/osboxes/Softwares
     become: yes
   - name: Move files
     command: mv /home/osboxes/Softwares/kafka_2.13-2.7.0 /usr/local/kafka
     become: yes