-
 name: Install MySQL Server
 hosts: dbservers
 tasks:
   - name: Install MySQL
     apt:
      name:  mysql-server
      state: present
     become: yes
   - name: Start the MySQL service
     become: yes
     service:
      name: mysql
      state: started
      enabled: true
