#!/bin/bash
### BEGIN INIT INFO
# Provides:  filters
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: filters service
### END INIT INFO
# /etc/init.d/fitlers: start the filters server.

# chkconfig: - 80 20
# description: filters

case $1 in
    start)
        /bin/bash /usr/local/bin/fitlers_start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/fitlers_stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/fitlers_stop.sh
       /bin/bash /usr/local/bin/fitlers_start.sh
    ;;
esac
exit 0
